name: Semantic Releases

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write
  packages: write
  statuses: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        # actions/checkout v4.3.0
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          persist-credentials: false

      - name: Setup Configuration
        run: |
          if [ -n "$GH_TOKEN_SECRET" ]; then
            echo "GH_TOKEN=$GH_TOKEN_SECRET" >> $GITHUB_ENV
          else
            echo "GH_TOKEN=$GITHUB_TOKEN" >> $GITHUB_ENV
          fi
        env:
          GH_TOKEN_SECRET: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node
        # actions/setup-node v4.4.0
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 'lts/*'

      - name: Semantic Release
        # cycjimmy/semantic-release-action pinned SHA
        uses: cycjimmy/semantic-release-action@9cc899c47e6841430bbaedb43de1560a568dfd16
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
